### PR TITLE
Support amqps://user:pass@host:port/vhost URLs

### PR DESCRIPTION
**Pull request by bruceadams**

### CODE REVIEW

**Comment by dch** [comment]
thanks for the PR! I see you submitted it upstream too. The main issue for tls in the past is that the amp crate has very poor OpenSSL support so this only works for older OpenSSL versions. Until that’s addressed this still needs to be an option and not the default.

What OS/arch and OpenSSL are you using here?

**Comment by bruceadams** [comment]
Ah! I have used rabbiteer with TLS successfully on macOS and was surprised that I couldn't even get a build on Linux in several attempts. (I failed to build it on Windows as well, but I barely know what I'm doing on Windows.)

I hadn't thought about OpenSSL version. I have two versions, the one bundled with macOS and one installed via [Homebrew](https://brew.sh). I didn't think about which OpenSSL got used in the build. Looks like the Homebrew version in `/usr/local/opt/openssl`:

```bash
$ otool -L target/release/rabbiteer
target/release/rabbiteer:
	/System/Library/Frameworks/Security.framework/Versions/A/Security (compatibility version 1.0.0, current version 58286.220.15)
	/usr/local/opt/openssl/lib/libssl.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.200.5)
	/usr/lib/libresolv.9.dylib (compatibility version 1.0.0, current version 1.0.0)
$ brew info openssl
openssl: stable 1.0.2r (bottled) [keg-only]
. . .
```

**Comment by dch** [comment]
On Sat, 30 Mar 2019, at 09:37, Bruce Adams wrote:
> Ah! I have used rabbiteer with TLS successfully on macOS and was 
> surprised that I couldn't even get a build on Linux in several 
> attempts. (I failed to build it on Windows as well, but I barely know 
> what I'm doing on Windows.)

Sadly pretty much everywhere else (linux, BSD) has OpenSSL 1.1+ as default, and the upstream amqp dependency has no intentions of fixing the TLS API breakage. Sad, as this is one of the thing I really like about rabbiteer. I'm a rust dabbler so no chance of me addressing it either.

**Comment by bruceadams** [comment]
Thanks for the additional detail! I'm mostly a dabbler in Rust as well. On top of that, OpenSSL is way far outside the realm of things I'm going to get anywhere near to working on. I'm fine with closing the pull request or leaving it open with no expectation that it'll get merged. Do you have a preference?

**Comment by bruceadams** [comment]
I'm pretty sure this PR has no value remaining open; closing…

**Comment by dch** [comment]
@bruceadams https://github.com/cloudamqp/amqpcat (crystal, so doesn't work on windows), or https://github.com/jgallagher/amiquip/tree/master/examples provide TLS support. I'm interested in the latter, as it comes with rust's native TLS layer and therefore no more OpenSSL pain ever again.

**Pull request closed without merging**
